//teste de requisições rest - alunos
@baseURL = http://localhost:4000/api

//ALUNOS
//GET - Listando os alunos
GET {{{baseURL}}}/aluno
Content-Type: application/json

###
//POST - Insere um novo aluno
POST {{{baseURL}}}/aluno
Content-Type: application/json

{
    "ra": "2",
    "nome": "Rafael Matos",
    "cpf": "516.492.987-47",
}

###
//DELETE - Excluindo um aluno pelo ra
DELETE {{{baseURL}}}/aluno/2
Content-Type: application/json

###
//PUT - Altera o novo aluno
PUT {{{baseURL}}}/aluno
Content-Type: application/json

{
    "ra": "2",
    "nome": "Rafael Gomes",
    "cpf": "516.492.987-68",
}

//PROFESSOR

//GET - Listando os professores
GET {{{baseURL}}}/professor
Content-Type: application/json

###
//POST - Insere um novo professor
POST {{{baseURL}}}/professor
Content-Type: application/json

{
"rf": "5648",
"nome": "Ana Carolina",
"cpf": "333.444.222-78",
"especialidade": "Biologia",
}

###
//DELETE - Excluindo um professor pelo rf
DELETE {{{baseURL}}}/professor/2
Content-Type: application/json

###
//PUT - Altera o novo professor
PUT {{{baseURL}}}/professor
Content-Type: application/json

{

"rf": "2314",
"nome": "Ana Bizarra",
"cpf": "123.764.422-08",
"especialidade": "Historia",

}