/*
criando login de acesso ao banco de dados 
*/

USE MASTER 
GO

--DROP LOGIN Escola;
CREATE LOGIN Escola WITH PASSWORD = '**SuaSenha**';
GO

GRANT CONNECT SQL TO Escola;
GO

USE ESCOLA
GO

--DROP USER Escola
CREATE USER Escola FOR LOGIN Escola;
GO

GRANT EXECUTE ON ESCOLA.dbo.SP_I_ESC_ALUNO TO Escola;
GRANT EXECUTE ON ESCOLA.dbo.SP_I_ESC_PROFESSOR TO Escola;
GRANT EXECUTE ON ESCOLA.dbo.SP_UP_ESC_ALUNO TO Escola;
GRANT EXECUTE ON ESCOLA.dbo.SP_UP_ESC_PROFESSOR TO Escola;
GRANT EXECUTE ON ESCOLA.dbo.SP_S_ESC_ALUNO TO Escola;
GRANT EXECUTE ON ESCOLA.dbo.SP_S_ESC_PROFESSOR TO Escola;
GRANT EXECUTE ON ESCOLA.dbo.SP_D_ESC_ALUNO TO Escola;
GRANT EXECUTE ON ESCOLA.dbo.SP_D_ESC_PROFESSOR TO Escola;
